### ISSUE TITLE
Remove client side dependencies

### ISSUE THREAD

**Issue by prowwid** [bedezign/yii2-audit#154]
When trying to install through composer got following error:

> Problem 1
>     - bedezign/yii2-audit 1.0.0 requires 2amigos/yii2-chartjs-widget 2.\* -> satisfiable by 2amigos/yii2-chartjs-widget[2.0.0].
>     - bedezign/yii2-audit 1.0.1 requires 2amigos/yii2-chartjs-widget 2.\* -> satisfiable by 2amigos/yii2-chartjs-widget[2.0.0].
>     - bedezign/yii2-audit 1.0.2 requires 2amigos/yii2-chartjs-widget 2.\* -> satisfiable by 2amigos/yii2-chartjs-widget[2.0.0].
>     - bedezign/yii2-audit 1.0.3 requires 2amigos/yii2-chartjs-widget 2.\* -> satisfiable by 2amigos/yii2-chartjs-widget[2.0.0].
>     - bedezign/yii2-audit 1.0.4 requires 2amigos/yii2-chartjs-widget 2.\* -> satisfiable by 2amigos/yii2-chartjs-widget[2.0.0].
>     - bedezign/yii2-audit 1.0.5 requires 2amigos/yii2-chartjs-widget 2.\* -> satisfiable by 2amigos/yii2-chartjs-widget[2.0.0].
>     - bedezign/yii2-audit 1.0.6 requires 2amigos/yii2-chartjs-widget 2.\* -> satisfiable by 2amigos/yii2-chartjs-widget[2.0.0].
>     - 2amigos/yii2-chartjs-widget 2.0.0 requires bower-asset/chartjs 1.0.2 -> no matching package found.
>     - Installation request for bedezign/yii2-audit ^1.0 -> satisfiable by bedezign/yii2-audit[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6].

The reason of failure is that package "2amigos/yii2-chartjs-widget" requires bower asset "bower-asset/chartjs". 
We do not use "fxp/composer-asset-plugin" in our project and won't be because for client side libraries we use bower without any plugins for composer. 

Forcing users to use "fxp/composer-asset-plugin" is not a good idea because not every one follow such approach of asset dependencies management. Even Yii team planned to drop fxp plugin support (see https://github.com/yiisoft/yii2/wiki/Plan-for-next-major-versions).
So I consider you to drop the requirement of  "2amigos/yii2-chartjs-widget" and find another way of client side dependencies management.

**Comment by cornernote** [comment]
The issue is the current supported way in Yii2 documentation is "fxp/composer-asset-plugin".  When that changes they will have documentation on using bower/npm.  If we change this then we will have to explain how to use bower/npm.

The problem is not so much with yii2-audit as it is with [yii2-chartjs-widget](https://github.com/2amigos/yii2-chartjs-widget), but the dependancy structure of yii2-audit makes it an issue for both.

The reason for the requirement of yii2-chartjs-widget is purely aesthetic, it provides some simple graphs on the module's default page.  

Removing it would have little impact, and graph setup could be optional and documented in the todo.  

Are you able to do a PR to make the graphs optional (a setting in the [Audit](https://github.com/bedezign/yii2-audit/blob/master/src/Audit.php#L49) class, and using that setting in [the view](https://github.com/bedezign/yii2-audit/blob/master/src/views/default/index.php)) and provide some basic docs that explain how to add `2amigos/yii2-chartjs-widget` to their composer.json ?

**Comment by DeathAngel** [comment]
Hello @cornernote,

Sorry for the late response - I was a really busy on work and had no time event to answer you. Now I have more free time and think in a next few weeks might come up with a solution. 
At this point, I see several ways to accomplish this task but need to analyze code base deeper to find the best way to make "view" part of the module more flexible.
In any case, I think changes will be backward incompatible and there will be more than one change in view files and code base. So if I'll start to implement this feature would you prefer to make all of the changes in a single PR or create several small PR for each change event if all of the changes connected?

With best regards,
Dmitry

**Comment by cornernote** [comment]
Hey @DeathAngel,

Just one PR would be preferable.
