### ISSUE TITLE
How to see the data

### ISSUE THREAD

**Issue by bobonov** [bedezign/yii2-audit#2]
Sorry to bother you but I do not understand if I'm missing something.
The module is installed and it works, I see the data in the db.

First problem
I didn't understand how to call the RequestController via browser.
Do I need to move it to my controller directory or it is possible to call it like directly?

Second problem
Looking to the controller code and related views I saw that **overview** view is missing

**Comment by Blizzke** [comment]
To be honest this module is far from finished. I started writing it with the intention of being able to share it for everyone. Unfortunately I was only able to get to to log. Other, more urgent, things came up and I haven't been able to visit this again since. I'm sorry that that wasn't made more clear in the readme, I've completely lost view of this.

**Comment by bobonov** [comment]
Ok so then I'll make my own interface and if the result is nice I'll send it to you.
By the way Tanks for your work!
PS can you check the issue 1 and update composer.json? I realy would like to avoid yii2 dev-master use

**Comment by Blizzke** [comment]
Yes, I will take care of that for you. When I first added it there was no stable version of Yii2 yet :)
