### ISSUE TITLE
CLI Don't save user identity

### ISSUE THREAD

**Issue by markmarco16** [bedezign/yii2-audit#210]
Hello team.

When have a cron with console command, don't register the user_id provider by Yii::$app->user->identity->id. Audit set by default "Guest"

![image](https://user-images.githubusercontent.com/4205973/28426462-3022d752-6d41-11e7-8aed-a96c3c5153ac.png)

I set identity user with next code:

```php
<?php
 
namespace app\commands;

use yii;
use yii\console\Controller;
use app\models\User;
use app\models\Subscription;
use app\models\SubscriptionOrder;
use app\models\Setting;

/**
 * Cron Tracking Controller
 */
class CronTrackingController extends Controller 
{
    public $user = 'interfazrastreo';

    /**
     *  Login User interface
     */
    public function init() {
        parent::init();
        Yii::$app->user->setIdentity(User::findOne(['username' => $this->user]));
    }
...
```

But I can not register the authenticated user console

**Comment by Blizzke** [comment]
It's not saving the user id on console because by default the console does not do users. [We explicitly check for this](https://github.com/bedezign/yii2-audit/blob/master/src/models/AuditEntry.php#L151). 

You'll have to add this manually to the entry. You could perhaps link to the `onAfterRequest` event before the Audit module is loaded and manually add the user id. It is a bit of an edge case that we can't support.
