### ISSUE TITLE
Trying to get property 'id' of non-object

### ISSUE THREAD

**Issue by juniorari** [bedezign/yii2-audit#277]
I have this error now, when i put to load assets on the view:
`\bedezign\yii2\audit\web\JSLoggingAsset::register($this);`

![image](https://user-images.githubusercontent.com/14263768/92663129-6af75400-f2ce-11ea-9b00-a6310a4e241f.png)

It only happens on log of javascript Class (vendor/bedezign/yii2-audit/src/web/JSLoggingAsset.php)

My common/config/main.php, configured properly: 
![image](https://user-images.githubusercontent.com/14263768/92663855-7ba8c980-f2d0-11ea-8d11-f0fb33dcfee6.png)

I try to uninstall and reinstall without successfully.

First
`composer remove bedezign/yii2-audit:"^1.1"`

And after:
`composer require --prefer-dist bedezign/yii2-audit:"^1.1"`

My solution was edit file vendor/bedezign/yii2-audit/src/web/JSLoggingAsset.php, this way:
![image](https://user-images.githubusercontent.com/14263768/92663897-924f2080-f2d0-11ea-89b7-83e84fc184c6.png)

And its works, and is capture log error javascript normally.

Any suggestion?

**Comment by eluhr** [comment]
It looks like you have a database component with the name "audit". At least that's what I infer from your screenshot ("db" => "audit"). 
This causes the Audit::getInstance() method to get confused.

I would suggest that you rename the database component to something like "auditDb". If this issue is still relevant for you at all.
