### ISSUE TITLE
Unable to locate message source for category 'audit'

### ISSUE THREAD

**Issue by raviteja1452** [bedezign/yii2-audit#6]
When I entered the URL to ../auditing to see the viewer , 
 Got this error 
..\yiisoft\yii2\i18n\I18N.php

Please help

**Comment by Blizzke** [comment]
There is indeed no translation file for the component because I still have to figure out how to adde the translations in a clean way to your generic configuration (afaik there is no "nice"way to specify translations for a module). I'll look into doing this asap. 

For now, you can bypass the by adding a translation entry with '*'. If you use MessageSource as the class it will just act as a dummy and no more errors will be triggered.

For example:
~~~
        'i18n' => [
           'translations' => [
               // By default all translations can be found in the database
                '*' =>  [
                   'class' => 'yii\i18n\MessageSource',
              ]
       ]
~~~  
Sorry about that.
