### ISSUE TITLE
panel grid functionality broken when switching from the default loaded one

### ISSUE THREAD

**Issue by Blizzke** [bedezign/yii2-audit#87]
You get a `jQuery('#whatever-grid-id').yiiGridView is not a function`. If you reload the url (with that panel selected) it works normally.

I suspect this is due to the added PJAX, as it did work perfectly before. 
(custom layout, not the default one)

**Comment by cornernote** [comment]
The reason is that the gridview JS is not loaded on the Request panel, but it is required on (for example) the Database panel.  As the database panel is loaded via pjax the JS never gets loaded.

The solution is to load the gridview JS (and all other panel JS for that matter on the first page).

This may be more effort than it's worth to have the pjax functionality.  Especially when we start dealing with custom panels.

**Comment by Blizzke** [comment]
You're right. Agree on the removing PJAX again.

**Comment by schmunk42** [comment]
Thanks for pointing out the issue. Additional JavaScript is a common problem with PJAX/AJAX, but I still overlook it from time to time.

I can't recall it ... does PJAX also removes inline JavaScript or is there an option to allow that?

**Comment by cornernote** [comment]
Even if we do, we then run the risk of double-parsing JS, which could lead to other issues.

Based on the problems its causing, and the value of pjax on this page, do you think it's worth looking further into it?

**Comment by schmunk42** [comment]
We'll look into this, because we've the same problem in giiant, but it will take some time.

**Comment by cornernote** [comment]
No probs, im curious if there is a good solution to this as i have had the issue before with ajax modals.
