### ISSUE TITLE
recommended to remove cascade

### ISSUE THREAD

**Issue by cornernote** [bedezign/yii2-audit#98]
what are your thoughts on removing the `CASCADE` on `audit_trail`?

```
$this->addForeignKey('fk_audit_trail_entry_id', self::TABLE, ['entry_id'], '{{%audit_entry}}', 'id', 'CASCADE');
```
https://github.com/bedezign/yii2-audit/blob/master/src/migrations/m150626_000004_create_audit_trail.php#L26

other tables can probably keep it, but this one, and also `audit_mail` would be useful data even if the entry was gone.

**Comment by Blizzke** [comment]
So are you proposing that you want a way to be able to keep these records, even without the associated entry? There probably might be some other changes involved as well to get that working in the viewer

**Comment by cornernote** [comment]
Now that I think about it more...  The entry should stay.  But you shouldn't just be able to cascade delete it without first deleting the related trails and mails.  Perhaps change to RESTRICT (which is the default if we remove cascade)

**Comment by cornernote** [comment]
this is related to #95

**Comment by Blizzke** [comment]
I agree with RESTRICT. IMO its not an issue that the entry has to stick around, since it contains almost no data after our optimalisations. 
Its easier to leave it there until all panels are removed than to modify the viewer everywhere with the possibility that the entry might already be gone. 

If we are attempting to clean the entries during a truncate we could probably just use `DELETE IGNORE` instead then.
